// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"kt/internal/biz"
	"kt/internal/conf"
	"kt/internal/data"
	"kt/internal/server"
	"kt/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db, err := data.NewGormDB(confData)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(confData, logger, db)
	if err != nil {
		return nil, nil, err
	}
	machineRepo := data.NewMachineRepo(dataData, logger)
	machineUseCase := biz.NewMachineUseCase(machineRepo, logger)
	getMachineService := service.NewGetMachineService(machineUseCase)
	grpcServer := server.NewGRPCServer(confServer, getMachineService, logger)
	httpServer := server.NewHTTPServer(confServer, getMachineService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
