version: '3.8'
services:
  # db:
  #   build: .
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root1234
  #     MYSQL_DATABASE: kratos
  #   volumes:
  #     - db_data:/var/lib/mysql

  mysql:
    image: bitnami/mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: kratos
      # MYSQL_USER: caldawin
      # MYSQL_PASSWORD: caldawin
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

volumes:
  db_data:
